--- #create file using linux commands
- hosts: all
  become: true
  connection: ssh
  user: moni

  tasks:
    - name: create folder
      file:
        path: /home/moni/pikachu
        state: directory

