--- # downloading multiple users
- hosts: all
  become: true
  user: moni
  connection : ssh

  tasks:
    - name: create users
      user: name="{{item}}" state=present
      with_items:
        - Pikachu
        - Shinchan
        - Doraemon
        - Mammu
        - Ram
        - Bhavya
