--- # tomcat installation
- hosts: all
  become: true



  tasks:
    - name: install java s/w on redhat
      yum:
        name: java
        state: installed
      when: ansible_os_family == "RedHat"

    - name: install java s/w on debian
      yum: 
        name: default-jdk
        state: present
      when: ansible_os_family == "Debian"


    - name: download tomcat s/w
      get_url:
         url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.17/bin/apache-tomcat-10.1.17.tar.gz
         dest: /opt



    - name: untar and unzip
      unarchive:
        src: /opt/apache-tomcat-10.1.17.tar.gz
        dest: /opt
        remote_src: yes


    - name: providing permissions
      file:
        path: /opt/apache-tomcat-10.1.17/bin/startup.sh
        mode: 0777




    - name: start tomcat service
      shell: nohup ./startup.sh
      args:
        chdir: /opt/apache-tomcat-10.1.17/bin

