--- #remove and stop https service
- hosts: moniansible
  become: true


  tasks:
    - name: remove pkg
      yum:
        name: httpd
        state: absent


    - name: stop service
      service:
        name: httpd
        state: stopped
